DROP TABLE t_rhstu_bairro CASCADE CONSTRAINTS;

DROP TABLE t_rhstu_cidade CASCADE CONSTRAINTS;

DROP TABLE t_rhstu_consulta CASCADE CONSTRAINTS;

DROP TABLE t_rhstu_consulta_forma_pagto CASCADE CONSTRAINTS;

DROP TABLE t_rhstu_contato_paciente CASCADE CONSTRAINTS;

DROP TABLE t_rhstu_email_paciente CASCADE CONSTRAINTS;

DROP TABLE t_rhstu_endereco_paciente CASCADE CONSTRAINTS;

DROP TABLE t_rhstu_estado CASCADE CONSTRAINTS;

DROP TABLE t_rhstu_forma_pagamento CASCADE CONSTRAINTS;

DROP TABLE t_rhstu_logradouro CASCADE CONSTRAINTS;

DROP TABLE t_rhstu_medicamento CASCADE CONSTRAINTS;

DROP TABLE t_rhstu_medico CASCADE CONSTRAINTS;

DROP TABLE t_rhstu_paciente CASCADE CONSTRAINTS;

DROP TABLE t_rhstu_paciente_plano_saude CASCADE CONSTRAINTS;

DROP TABLE t_rhstu_plano_saude CASCADE CONSTRAINTS;

DROP TABLE t_rhstu_prescicao_medica CASCADE CONSTRAINTS;

DROP TABLE t_rhstu_telefone_paciente CASCADE CONSTRAINTS;

DROP TABLE t_rhstu_tipo_contato CASCADE CONSTRAINTS;

DROP TABLE t_rhstu_unid_hospitalar CASCADE CONSTRAINTS;

DROP SEQUENCE SQ_RHSTU_ESTADO;

DROP SEQUENCE SQ_RHSTU_CIDADE;

DROP SEQUENCE SQ_RHSTU_BAIRRO;

DROP SEQUENCE SQ_RHSTU_LOGRADOURO;

DROP SEQUENCE SQ_RHSTU_TIPO_CONTATO;

DROP SEQUENCE SQ_RHSTU_ENDERECO_PACIENTE;

DROP SEQUENCE SQ_RHSTU_UNID_HOSPITALAR;

DROP SEQUENCE SQ_RHSTU_MEDICO;

DROP SEQUENCE SQ_RHSTU_MEDICAMENTO;

DROP SEQUENCE SQ_RHSTU_PRESCRICAO_MEDICA;

DROP SEQUENCE SQ_RHSTU_PACIENTE;

DROP SEQUENCE SQ_RHSTU_PLANO_SAUDE;

DROP SEQUENCE SQ_RHSTU_EMAIL_PACIENTE;

DROP SEQUENCE SQ_RHSTU_PACIENTE_PLANO_SAUDE;

DROP SEQUENCE SQ_RHSTU_FORMA_PAGAMENTO;

DROP SEQUENCE SQ_RHSTU_CONSULTA_FORMA_PAGTO;

DROP SEQUENCE SQ_RHSTU_CONTATO_PACIENTE;

DROP SEQUENCE SQ_RHSTU_TELEFONE_PACIENTE;

DROP SEQUENCE SQ_RHSTU_CONSULTA;